apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-demo
spec:
  data:
#Add your key-value pairs here
    project: roboshop
    environment: production
    log_level: verbose
    
    game.properties: |
      enemy.types=aliens,monsters
      player.maximum-lives=5 


apiVersion: v1
kind: Pod 
metadata: 
  name: config-pod
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - configMapRef:
        name: configmap-demo