apiVersion: v1
kind: Service
metadata: 
  name: service-demo-nginx
spec:
  selector: 
    app: roboshop
    environment: dev
  ports:
  - protocol: TCP 
    port: 80 # service port
    targetPort: 80 # container port

